name: "Python Builder"
run-name: Running build by ${{ github.actor }}
on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: macos-latest
            name: darwin
          - os: ubuntu-latest
            name: linux
          - os: windows-latest
            name: win

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.8"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Build package with pyinstaller on ${{ matrix.os }}
        run: uv run pyinstaller --onefile gfeed.py --name gfeed-${{matrix.name}}

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: gfeed-${{ matrix.os }}
          path: dist/*

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/
          pattern: gfeed-*

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/gfeed-*
